twig:
    file_name_pattern: '*.twig'
    globals:
        frontend_base_url: '%env(FRONTEND_URL)%'
        project_name: '%env(COMPOSE_PROJECT_NAME)%'
when@test:
    twig:
        strict_variables: true
